### ISSUE TITLE
Cannot exit terminal after registering enemy

### ISSUE THREAD

**Issue by NotCasey** [EvaisaDev/LethalLib#45]
`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Terminal.QuitTerminal () (at <af9b1eec498a45aebd42601d6ab85015>:IL_000B)
Terminal.PressESC (UnityEngine.InputSystem.InputAction+CallbackContext context) (at <af9b1eec498a45aebd42601d6ab85015>:IL_0013)
UnityEngine.InputSystem.Utilities.DelegateHelpers.InvokeCallbacksSafe[TValue] (UnityEngine.InputSystem.Utilities.CallbackArray1[System.Action1[TValue]]& callbacks, TValue argument, System.String callbackName, System.Object context) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:IL_001B)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)

[Error  : Unity Log] NullReferenceException while executing 'performed' callbacks of 'Movement/OpenMenu[/Keyboard/escape,/Keyboard/tab]`

**Comment by AnotherCrab1** [comment]
so if you cant escape terminal try downloading terminal mod with leave command like darmuhs terminal stuff
or something like that

**Comment by Hamunii** [comment]
I'm assuming this was an incompatibility and has been fixed since because I haven't heard of this. I know LethalLevelLoader has had issues with breaking the terminal in some way, but idk if LLL even existed when this issue was opened.

Anyways, I'm closing this since this is old and there isn't much info, like what mods were used, and doesn't seem to be a problem anyone has had in a while.
