### ISSUE TITLE
Generating loot behind textures

### ISSUE THREAD

**Issue by Paradox75831004** [EvaisaDev/LethalLib#48]
A bug in generating loot in textures; the minimap shows that the loot is somewhere nearby, but in fact it is nowhere to be found. Either these are mods with Scrap like this or the settings in the library are wrong, I don’t know... I don’t understand

Mod assembly code - 018d1bfa-9ed3-3536-9016-86b2af0d3b82

Shows what is there somewhere, but at what level? Higher? Below? Unclear. Most of the mods on Scrap are related to your library, this never happened before, we didn’t notice this on the radar (I used the minimap to find errors)
![image](https://github.com/EvaisaDev/LethalLib/assets/72872478/00f70f5b-5069-4ac0-a50f-b5798fbf3eb8)
![image](https://github.com/EvaisaDev/LethalLib/assets/72872478/b885240d-b223-4e96-9505-132fec53597f)

**Comment by Paradox75831004** [comment]
There is also a problem - when you dump things on an iron grid in the complex - sometimes they fall through. Is this a problem of the game or libraries?

**Comment by Hamunii** [comment]
LethalLib's job is only to register items, and the game or the items themselves deal with what they should, collision things probably LethalLib's problem. Also modded items being invisible is probably the modded item's problem, since I've never heard of this being an issue before.

Since this is very unlikely to be either the issue of the modded scrap you were using, or a base-game bug, or a conflicting mod, I'm closing this.
