### ISSUE TITLE
v50 update entity error

### ISSUE THREAD

**Issue by Berddd** [EvaisaDev/LethalLib#76]
As of right now, Lethallib breaks entity spawns in v50.

**Comment by Spark61** [comment]
same issue

**Comment by LeonardoLoa** [comment]
same

**Comment by IanSPACCA** [comment]
it's been confirmed that is a problem with LethalLib

**Comment by Aeniema** [comment]
What errors with spawns? Nothing on my end other than with Scopo.

**Comment by Azure0219** [comment]
@Aeniema all enemy spawns, indoors and outdoors. I tested this last night. Even on eclipsed moons, monsters don't spawn.
This is reproducible on my end by disabling/re-enabling anything associated to lethallib. 
 Interestingly if FacilityMeltdown is also running, that is able to spawn enemies indoors when the Apparatus is taken.

**Comment by EvaisaDev** [comment]
I am not able to reproduce this without other mods.
If I install LethalLib and LethalThings everything works as normal on v50, including lethal things modded enemy spawns.
So it must be another mod breaking things, or some interaction 🤷‍♀️

**Comment by PontusFrykter** [comment]
> I am not able to reproduce this without other mods. If I install LethalLib and LethalThings everything works as normal on v50, including lethal things modded enemy spawns. So it must be another mod breaking things, or some interaction 🤷‍♀️

018eec7c-f020-4e3b-01c5-2981571c6ffc

Here, reproduce it.

**Comment by EvaisaDev** [comment]
Sorry but I am not going to look into an issue that only happens when another mod is installed.
I am not actively maintaining this mod at this point so compatibility is not one of my concerns.
If the mod works fine on its own and alongside lethalthings, that tells me the mod works fine, and it ain't my problem.

**Comment by Ulfurvojn** [comment]
Hi there.

Posting here because I thought I had the same issue ; however, as EvaisaDev said and thanks to some cross-testing between PontusFrykter's modpack and mine, I was able to determine that the problem indeed does not come from LethalLib, but rather from LethalLevelLoader (every version is currently bugged on my end, even the newest fix) and Scopophobia.

So, it's kind of a bother but I suggest not trying to play with new moons and/or interiors at the time and disabling Scopophobia as well. 

Another thing to note : LCSoundTool logs an error with networking in both our packs, and while the game runs perfectly playing solo I think it might cause issues while hosting (I know nothing about modding or networking though).

So yeah, just wanted to clarify that so the issue can be closed and people can stop accusing LethalLib of breaking the game.

**Comment by Falcion** [comment]
Check on mods like "MaskedEnemyOverhaul"(\*1) and "Skinwalkers"(\*2):
\*1: it is very outdated and it was a charm that it was working until V50, you can check it's repository, this mod is stale.
\*2: LC's modding server is saying that "Skinwalkers" mod is updated to the last version, but it can also make this entity's errors, if you want to play with this-alike mod, I recommend "Mirage".

Helped for me, but this case is very unstable because of a huge number of mobs that are unsupported on new versions, there are some quotes with data:

> Can’t add a lot of entities mods to my mod pack, Shy guy, Locker, Forest Giant family, they stop everything from spawning, except for old birds in their dormant state (allitheorchid)

> a lot of enemy related mods are broken (iambatby)

> I know some mods have been MaskedEnemyOverhaul, Scopophobia, and Skinwalkers. Though I don't have any of those and I am also getting this same issue, so I don't know what else beyond those 3. (nemesis041)

> hey im using some mods, and since the v50 update no creatures spawn(including vanilla and the stationary old birds on embrion ) is there a fix? I run a handful of mods, and this is all of them. The deprecated mod still worked and the game functioned as normal on v45 with that deprecated mod on so i know that is not the issue (thearchives)

**Answer (^):**

> its masked enemy overhaul
> replace it and skinwalkers with the mirage mod (explodingturtles456)

I recommend to you to go in LC's modding discord server and talk about this troubleshooting elsewhere but this repository, even if developer wanted, he can't fix other mods that are stale or etc.

**Comment by dev-ainz** [comment]
What is the latest version without this problem?

**Comment by Azure0219** [comment]
Can confirm, I uninstalled Skinwalkers and installed Mirage with lethallib and its dependencies also enabled and didn't have any issues afterwards.

**Comment by Falcion** [comment]
@EvaisaDev,
It seems to me that this issue can be closed and pinned in issues page; in the future, in case of such errors, it will be possible to simply redirect users to this topic.

What's your opinion about such resolution of this issue?
